#!/bin/bash

FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(c|h)$')

if [ -z "$FILES" ]; then
    exit 0
fi

echo "--- [1/3] Checking Clang-Format"
clang-format -style=Google -n $FILES

echo "--- [2/3] Running cppcheck"
cppcheck --enable=warning,performance,portability \
         --error-exitcode=1 \
         --suppress=missingIncludeSystem \
         --inline-suppr \
         $FILES
if [ $? -ne 0 ]; then
    echo -e "\033[0;31m[err] Cppcheck found errors. commit aborted\033[0m"
    exit 1
fi

echo "--- [3/3] Building"
cmake -B build && cmake --build build -j$(nproc)
if [ $? -ne 0 ]; then
    echo -e "\033[0;31m[err] cannot build. commit aborted\033[0m"
    exit 1
fi
echo -e "\033[0;32m[success]pre-commit hook approved the commit.\033[0m"
exit 0